
services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

  backend:
    build:
      context: ./server
    container_name: backend
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - UPLOAD_PATH=${UPLOAD_PATH}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - mongodb
    ports:
      - "8080:8080"
    command: ["sh", "-c", "npm run seed && node dist/app"]

  frontend:
    build:
      context: ./client
    container_name: frontend
    depends_on:
      - backend
    ports:
      - "80:80"  

volumes:
  mongo-data:
