services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

  traveltime-server:
    build:
      context: ./server
    container_name: traveltime-server
    environment:
      - MONGO_URI=${MONGO_URI}
      - PORT=${PORT}
      - HOST=${HOST}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_REGION=${AWS_REGION}
      - AWS_ROLE_ARN=${AWS_ROLE_ARN}
      - LOCAL_STORAGE_PATH=${LOCAL_STORAGE_PATH}
      - STORAGE_TYPE=${STORAGE_TYPE}
      - LOCAL_STORAGE_BASE_URL=${LOCAL_STORAGE_BASE_URL}
    depends_on:
      - mongodb

  frontend:
    build:
      context: ./client
      args:
      - NGINX_CONF=nginx.local.conf
    container_name: frontend
    depends_on:
      - traveltime-server
    ports:
      - "80:80"

  seeder:
    build:
      context: ./server  # Same as backend build
    container_name: seeder
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
    command: ["sh", "-c", "node dist/scripts/seed.js"]
    restart: "no"  # Ensures it runs only once and exits


volumes:
  mongo-data:
