services:
  mongodb:
    image: mongo:6.0
    container_name: mongodb
    volumes:
      - mongo-data:/data/db

  travel-time-server:
    build:
      context: ./server
    container_name: travel-time-server
    environment:
      - MONGO_URI=${MONGO_URI}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - JWT_REFRESH_SECRET_KEY=${JWT_REFRESH_SECRET_KEY}
      - AWS_BUCKET_NAME=${AWS_BUCKET_NAME}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_SESSION_TOKEN=${AWS_SESSION_TOKEN}
      - AWS_REGION=${AWS_REGION}
    depends_on:
      - mongodb
    # command: ["sh", "-c", "npm run seed && node dist/app"]

  frontend:
    build:
      context: ./client
    container_name: frontend
    depends_on:
      - travel-time-server
    ports:
      - "80:80"  

  seeder:
    build:
      context: ./server  # Same as backend build
    container_name: seeder
    depends_on:
      - mongodb
    environment:
      - MONGO_URI=${MONGO_URI}
    command: ["sh", "-c", "node dist/scripts/seed.js"]
    restart: "no"  # Ensures it runs only once and exits


volumes:
  mongo-data:
