apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-time-server
  labels:
    app: travel-time-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-time-server
  template:
    metadata:
      labels:
        app: travel-time-server
    spec:
      containers:
        - name: travel-time-server
          image: mmarci96/travel-time-server:latest
          ports:
            - containerPort: 8080
          envFrom:
            - secretRef:
                name: travel-time-server-secrets
            - configMapRef:
                name: travel-time-server-config 
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "128Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 5
            periodSeconds: 10
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /health
              port: 8080
            initialDelaySeconds: 10
            periodSeconds: 20

