
apiVersion: apps/v1
kind: Deployment
metadata:
  name: travel-time-client
  labels:
    app: travel-time-client
spec:
  replicas: 2
  selector:
    matchLabels:
      app: travel-time-client
  template:
    metadata:
      labels:
        app: travel-time-client
    spec:
      containers:
        - name: travel-time-client
          image: 390403884602.dkr.ecr.eu-north-1.amazonaws.com/traveltime/travel-time-client:latest
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: "64Mi"
              cpu: "50m"
            limits:
              memory: "128Mi"
              cpu: "100m"
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 10
            periodSeconds: 20

